/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Clases.Socio;
import DAO.SocioDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Vista.FrSocioAdd;
import java.awt.Color;
/**
 *
 * @author Diego
 */
public class FRSocio extends javax.swing.JFrame {
    SocioDAO socDAO = new SocioDAO();

    /**
     * Creates new form FRSocio
     */
    public FRSocio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupEstado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPedido = new javax.swing.JTextPane();
        BtEliminar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("SOCIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, 30));

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Sede", "Estado", "NRegistro", "FechaInscripcion", "MesIngreso", "FechaRecepcion", "FormaPago", "MesDesc", "PuestroTrabajo", "Asociado", "Ci", "Telefono", "Email", "Beneficiario", "EmpresaRutEmpresa"
            }
        ));
        jScrollPane3.setViewportView(jTabla);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 1220, 160));

        jPanel2.setBackground(new java.awt.Color(82, 196, 88));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-trabajadores-masculinos-24.png"))); // NOI18N
        jLabel18.setText("Todo");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel18MousePressed(evt);
            }
        });
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 14, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-casa-24.png"))); // NOI18N
        jLabel19.setText("Principal ");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel19MousePressed(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 12, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-trabajador-de-sexo-masculino-24.png"))); // NOI18N
        jLabel20.setText("Socio");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel20MousePressed(evt);
            }
        });
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 12, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-empresa-25.png"))); // NOI18N
        jLabel21.setText("Empresa");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel21MousePressed(evt);
            }
        });
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 12, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8-hombre-de-negocios-24.png"))); // NOI18N
        jLabel22.setText("Persona ");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel22MousePressed(evt);
            }
        });
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 14, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 50));

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 140, -1, -1));

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, -1, -1));

        txtPedido.setText("Ingrese Ci a buscar");
        txtPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPedidoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtPedido);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 120, -1));

        BtEliminar.setText("Eliminar");
        BtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(BtEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FrSocioAdd frsa = new FrSocioAdd();
        frsa.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            listar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado al listart"+e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEliminarActionPerformed
//
//        int c;
//        try {
//            c = jTabla.getSelectedRow();
//            lista.remove(c);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Favor escojer un socio en la tabla");
//        }
//        listar();
        
        
        try {
            String ci = "'"+ txtPedido.getText()+"'";
            
            if(socDAO.eliminarSocio(ci)){
                JOptionPane.showMessageDialog(this, "El Socio no fue se pudo borrar eliminado");
            }else{
                JOptionPane.showMessageDialog(null, "Socio Eliminado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR EN Eliminar"+e.getMessage());
        }
    }//GEN-LAST:event_BtEliminarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            buscarLista(txtPedido.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado al listart por busqueda" + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtPedidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPedidoMousePressed
        // TODO add your handling code here:
        if (txtPedido.getText().equals("Ingrese Ci a buscar")) {
            txtPedido.setText("");
            txtPedido.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPedidoMousePressed

    private void jLabel18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MousePressed
        // TODO add your handling code here:
        FrSocioAdd frsa = new FrSocioAdd();
        frsa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel18MousePressed

    private void jLabel22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MousePressed
        // TODO add your handling code here:
        FRPersonaVer frpv = new FRPersonaVer();
        frpv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel22MousePressed

    private void jLabel19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MousePressed
        // TODO add your handling code here:
        JFPrincipal jfpr = new JFPrincipal();
        jfpr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel19MousePressed

    private void jLabel20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel20MousePressed

    private void jLabel21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MousePressed
        // TODO add your handling code here:
        JFEmpresaAdd jfrea = new JFEmpresaAdd();
        jfrea.setVisible(true);;
        this.setVisible(false);
    }//GEN-LAST:event_jLabel21MousePressed

    
    public void listar(){
        try {
       
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("SEDE");
            dtm.addColumn("ESTADO");
            dtm.addColumn("NREGISTRO");
            dtm.addColumn("FECHAINSCRIPCION");
            dtm.addColumn("MESINGRESO");
            dtm.addColumn("FECHARECEP");
            dtm.addColumn("FORMAGOPAGO");
            dtm.addColumn("MESDESC");
            dtm.addColumn("PUESTOTRABJO");
            dtm.addColumn("ASOCIADO");
            dtm.addColumn("CI");
            dtm.addColumn("TELEFONO");
            dtm.addColumn("EMAIL");
            dtm.addColumn("BENEFICIARIO");
            dtm.addColumn("RUTEMPRESA");
            
            List<Socio> lista = new SocioDAO().ListarSocio();
            String[] filas  = new String[15];
            
            for (Socio socio : lista) {
                filas[0] = socio.getSede();
                filas[1] = String.valueOf(socio.getEstado());
                filas[2] = String.valueOf(socio.getnRegistro());
                filas[3] = socio.getFechaInscripcion();
                filas[4] = socio.getMesIngreso();
                filas[5] = socio.getFechaRecepcion();
                filas[6] = socio.getFormaPago();
                filas[7] = socio.getMesDesc();
                filas[8] = socio.getPuestroTrabajo();
                filas[9] = socio.getAsociado();
                filas[10] = socio.getCi();
                filas[11] = String.valueOf(socio.getTelefono());
                filas[12] = socio.getEmail();
                filas[13] = socio.getBeneficiario();
                filas[14] = socio.getEmpresaRutEmpresa();
                
                dtm.addRow(filas);
            }
            jTabla.setModel(dtm);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en Tabla "+e.getMessage());
        }
}
        public void buscarLista(String ci) {
        try {

            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("SEDE");
            dtm.addColumn("ESTADO");
            dtm.addColumn("NREGISTRO");
            dtm.addColumn("FECHAINSCRIPCION");
            dtm.addColumn("MESINGRESO");
            dtm.addColumn("FECHARECEP");
            dtm.addColumn("FORMAGOPAGO");
            dtm.addColumn("MESDESC");
            dtm.addColumn("PUESTOTRABJO");
            dtm.addColumn("ASOCIADO");
            dtm.addColumn("CI");
            dtm.addColumn("TELEFONO");
            dtm.addColumn("EMAIL");
            dtm.addColumn("BENEFICIARIO");
            dtm.addColumn("RUTEMPRESA");

            List<Socio> lista = new SocioDAO().ListarSocio();
            String[] filas = new String[15];
            for (Socio socio : lista) {
                if(socio.getCi().equals(ci)){
                filas[0] = socio.getSede();
                filas[1] = String.valueOf(socio.getEstado());
                filas[2] = String.valueOf(socio.getnRegistro());
                filas[3] = socio.getFechaInscripcion();
                filas[4] = socio.getMesIngreso();
                filas[5] = socio.getFechaRecepcion();
                filas[6] = socio.getFormaPago();
                filas[7] = socio.getMesDesc();
                filas[8] = socio.getPuestroTrabajo();
                filas[9] = socio.getAsociado();
                filas[10] = ci;
                filas[11] = String.valueOf(socio.getTelefono());
                filas[12] = socio.getEmail();
                filas[13] = socio.getBeneficiario();
                filas[14] = socio.getEmpresaRutEmpresa();

                dtm.addRow(filas);
                }
            }
            jTabla.setModel(dtm);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en Tabla " + e.getMessage());
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRSocio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtEliminar;
    private javax.swing.ButtonGroup groupEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTabla;
    private javax.swing.JTextPane txtPedido;
    // End of variables declaration//GEN-END:variables
}
